### ISSUE TITLE
As a user I would like to be prompted to end the game when all treasures are found so that the game can have an end.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#11]
As a user I would like to be prompted to end the game when all treasures are found so that the game can have an end.

__Acceptance Criteria:__
* System detects when the final treasure is collected and displays the game finish image.
* System navigates to the input high score activity.

**Comment by ghost** [comment]
This is connected to ShowTreasureActivity and ShowTreasureLayout, refer here: https://docs.google.com/drawings/d/13C1PFRTgC9ncvL9tF-IZezcUuSIRlnQTmD3RrmmPRLo/edit?usp=sharing

**Comment by ghost** [comment]
Done.
