### ISSUE TITLE
As a user I would like to have the treasures disappear from the program when collected so that the same treasure isn't collected twice.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#12]
As a user, I would like to have the treasures disappear from the program when collected so that the same treasure isn't collected twice.

__Acceptance Criteria:__

* The system detects when the user is within N units of the treasure objects coordinates.  
* System indicates to the user that the treasure object has been collected.
* System navigates back to the FindTreasure or GameComplete layout depending on the status of the game post treasure collection.

**Comment by ghost** [comment]
This is connected to FindTreasureLayout and FindTreasureActivity. Refer here: https://docs.google.com/drawings/d/13C1PFRTgC9ncvL9tF-IZezcUuSIRlnQTmD3RrmmPRLo/edit?usp=sharing

**Comment by ghost** [comment]
Done
