### ISSUE TITLE
As a User I would like to be able to visit a website and input locations for treasures so that I can create custom game.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#13]
As a user I would like to be able to visit a website and input locations for treasures so that I can create a custom game. 

__Acceptance Criteria:__
* Website displays a graphical representation of a location (i.e. a map).
* Website allows for a user to select locations on the map for treasures to spawn.
* System allows the user to get the latitude and longitude coordinates of each treasure placed for saving to a file.

**Comment by RafaelELopez** [comment]
Aziz & Huseen

**Comment by ghost** [comment]
Done
