### ISSUE TITLE
As a user I would like the state of the game to be saved to the device so that my information can be saved between games.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#16]
As a user I would like the state of the game to be saved to the device so that my information can be saved between games.

__Acceptance Criteria:__
* System stores current game state when Yes to save is selected.
* System does not store current game state when No to save is selected.
* System enables resume game when a game state has been saved.
* System enables resume game on launch if a saved game can be loaded.

**Comment by ghost** [comment]
Do we want to save current game progress? Possibly triggers when the user presses the back button while in the FindTreasureLayout. refer here: https://docs.google.com/drawings/d/13C1PFRTgC9ncvL9tF-IZezcUuSIRlnQTmD3RrmmPRLo/edit

**Comment by ghost** [comment]
Need feedback
