### ISSUE TITLE
As a user I would like to see a high-score board so that I can compare my score with others playing the game.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#17]
As a user I would like to see a high-score board so that I can compare my score with others paying the game.

__Acceptance Criteria:__
* High scores should be saved and retrieved from the user device.
* System persists 3-character user names with scores from game to game.
* System loads and displays the top N scores to the user.

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
Need feedback
