### ISSUE TITLE
As a user I would like to see an about screen from the main menu, with details about the project and the developers.

### ISSUE THREAD

**Issue by ghost** [Omodi/TreasureHunt#24]
Elaboration:

The about screen shall show the 7 developer names and email addresses.
The about screen shall show the project title and the brief project description.
The about screen shall have a URL to the github repo.
The about screen should be accessible from the main menu.

**Comment by jdh6660** [comment]
The about screen shale show the 7 developer names and email addresses.
The about screen shale show the project title and the brief project description.
The about screen shale have a URL to the github repo.
The about screen should be accessible from the main menu.
