### ISSUE TITLE
As a user I would like to import a list of locations from a file via SD card so that I could make and run a custom game.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#26]
As a user I would like to import a list of locations generated by a user so that I can play a custom game.

__Acceptance Criteria:__

* ~~System gives user list of files in external SD card to allow their choice of a file .~~
* System successfully imports treasure location data from the ~~chosen~~given CSV file.
* System generates a new game based off of the imported treasure location data.

**Comment by ghost** [comment]
What were story points for this? Can you please elaborate this, look at other user stories for how we're elaborating them.

**Comment by cgv2921** [comment]
This was made quickly because it had to be at the time.  We were gonna go over it as a team one sprint day, but we ran out of time that day.  I can't add story points to it as that is a team activity, though I might be able to add acceptance criteria to it.

**Comment by ghost** [comment]
How to add a file to SD card: http://stackoverflow.com/questions/2808632/manually-put-files-to-android-emulator-sd-card

**Comment by cgv2921** [comment]
This User Story's acceptance criteria has been cut back to their original state based on time constraints.

**Comment by ghost** [comment]
Done
