### ISSUE TITLE
As a user I would like to see the treasure so that I can collect it

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#6]
As a user, I would like to see the treasure so that I can collect it.

__Acceptance Criteria:__

* Treasure graphics are displayed in the FindTreasureView.
* View accepts yaw and distance values for a number of treasures to be placed on the view. 
* The treasure indicator can move in response to changes in the yaw of the Vuzix to represent its location.
* The graphic indicates distance from the user to the treasure (e.g. transparency)

**Comment by cgv2921** [comment]
As a user I would like to see the treasure so that I can collect it.

**Comment by RafaelELopez** [comment]
Nathan, Colton, & Jeff

**Comment by ghost** [comment]
Treasure pick up screen now exists.

**Comment by ghost** [comment]
Here is what I thought we could do for the finding treasure layout. I've got most of the sensor/logic working. I just need to figure out bitmaps and canvases on Android.
https://docs.google.com/drawings/d/13C1PFRTgC9ncvL9tF-IZezcUuSIRlnQTmD3RrmmPRLo/edit?usp=sharing
