### ISSUE TITLE
As a user I would like to achieve points as I find treasures so that I am motivated to find more.

### ISSUE THREAD

**Issue by cgv2921** [Omodi/TreasureHunt#9]
As a user I would like to achieve points as I find treasures so that I am motivated to find more.

__Acceptance Criteria:__
* A user's coin total indicator is correctly adjusted on treasure collection.
* Upon finding a treasure, a user earns 100 coins.
* Coins are used to purchase upgrades
* Coins only last during the game, and are therefore lost when the game ends
* Coins are displayed on the -- FindTreasureLayout and ShowTreasureLayout-- view.

**Comment by ghost** [comment]
This appears to relate to User Story #10.

**Comment by ghost** [comment]
* Upon finding a treasure, a user earns 100 coins. (DONE)
* Coins only last during the game, and are therefore lost when the game ends (DONE)
